
<a href="javascript:void(0)" class="widget widget-hover-effect1" style="background-color:#394263" data-toggle="popover" data-content="Completo set de indicadores para mejorar la toma de decisiones." title="" data-original-title="No disponible en esta versión">
<div class="widget-simple">
<div class="widget-icon themed-background-autumn animation-fadeIn text-center" style="margin: 0 45px; background-color:#EAC50D !important;">
<i class="fa fa-plus-circle"></i>
</div>
<h3 class="widget-content text-center animation-pullDown">
Nueva <strong>Solicitud</strong><br>
</h3>
</div>
</a>

<a href="javascript:void(0)" class="widget widget-hover-effect1" style="background-color:#394263" data-toggle="popover" data-content="Entrega presupuesto de tesorería en base a datos precargados." title="" data-original-title="No disponible en esta versión">
<div class="widget-simple">
<div class="widget-icon themed-background-autumn animation-fadeIn text-center" style="margin: 0 45px; background-color:#35961C !important;">
<i class="fa fa-search"></i>
</div>
<h3 class="widget-content text-center animation-pullDown">
Consultar <strong>Solicitud</strong><br>
</h3>
</div>
</a>

<a href="javascript:void(0)" class="widget widget-hover-effect1" style="background-color:#394263;  padding-top:25px;" data-toggle="popover" data-content="Permite realizar análisis entre distintos períodos." title="" data-original-title="No disponible en esta versión">
<div class="widget-simple">
<div class="widget-icon themed-background-autumn animation-fadeIn text-center" style="margin: 0 45px;">
<i class="fa fa-check"></i>
</div>
<h3 class="widget-content text-center animation-pullDown">
Evaluar <strong>Servicio</strong><br>
</h3>
</div>
</a>

<a href="javascript:void(0)" class="widget widget-hover-effect1" style="background-color:#394263" data-toggle="popover" data-content="Permite comparar distintos períodos en base a diversos criterios." title="" data-original-title="No disponible en esta versión">
<div class="widget-simple">
<div class="widget-icon themed-background-autumn animation-fadeIn text-center" style="margin: 0 45px; background-color:#8A6D3B !important; ">
<i class="fa fa-file-text"></i>
</div>
<h3 class="widget-content text-center animation-pullDown">
Formularios <strong>Instructivos</strong><br>
</h3>
</div>
</a>