			<div id="modal-large" class="modal" tabindex="-1" role="dialog" aria-hidden="true">
				<div class="modal-dialog modal-lg">
					<div class="modal-content">
						<div class="modal-header">
							<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
							<h3 class="modal-title">Modal Title</h3>
						</div>
						<div class="modal-body">
							<div id="graph"></div>
						</div>
						<div class="modal-footer">
							<button type="button" class="btn btn-sm btn-default" data-dismiss="modal">Close</button>
							<button type="button" class="btn btn-sm btn-primary">Save changes</button>
						</div>
					</div>
				</div>
			</div>