
<nav class="navbar navbar-default navbar-inverse navbar-fixed-top" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <!-- logo -->
      <a href="<?php print($this->url->get('')) ?>" class="navbar-brand navbar-brand-fix"><img alt="" src="<?php print($this->url->get("img/logo.png"))?>"/></a>
      <
    </div>
    <div class="collapse navbar-collapse animated fadeIn" id="bs-example-navbar-collapse-1">
      <!--<ul class="nav navbar-nav animated fadeIn text16">
        
        <li class="<?php print($menuSel == "vacaciones"? 'active':'');?>"><a href="<?php print($this->url->get('vacaciones')) ?>"><i class="gi gi-cogwheel"></i>   Vacaciones</a></li></li>
        <li><a href="#"><span class="glyphicon glyphicon-download-alt"></span></a></li>
      </ul>-->
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>