<!DOCTYPE html>
<!--[if IE 8]>         <html class="no-js lt-ie9"> <![endif]-->
<!--[if IE 9]>         <html class="no-js lt-ie10"> <![endif]-->
<!--[if gt IE 9]><!--> <html class="no-js"> <!--<![endif]-->
<head>
	<meta charset="utf-8">

	<title><?php print($this->config->appTitle)?></title>

	<meta name="description" content="<?php print($this->config->appTitle)?>">
	<meta name="author" content="<?php print($this->config->appAutor)?>">
	<meta name="robots" content="noindex, nofollow">

	<meta name="viewport" content="width=device-width,initial-scale=1,maximum-scale=1.0">

	<!-- Icons -->
	<!-- The following icons can be replaced with your own, they are used by desktop and mobile browsers -->
	<link rel="shortcut icon" href="assets/img/favicon.png">
	<link rel="apple-touch-icon" href="assets/img/icon57.png" sizes="57x57">
	<link rel="apple-touch-icon" href="assets/img/icon72.png" sizes="72x72">
	<link rel="apple-touch-icon" href="assets/img/icon76.png" sizes="76x76">
	<link rel="apple-touch-icon" href="assets/img/icon114.png" sizes="114x114">
	<link rel="apple-touch-icon" href="assets/img/icon120.png" sizes="120x120">
	<link rel="apple-touch-icon" href="assets/img/icon144.png" sizes="144x144">
	<link rel="apple-touch-icon" href="assets/img/icon152.png" sizes="152x152">
	<link rel="apple-touch-icon" href="assets/img/icon180.png" sizes="180x180">
	<!-- END Icons -->

	<!-- Stylesheets -->
	<!-- Bootstrap is included in its original form, unaltered -->
    <?php print($this->tag->stylesheetLink("css/bootstrap.min.css"))?>

	<!-- Related styles of various icon packs and plugins -->
    <?php print($this->tag->stylesheetLink("css/plugins.css"))?>

	<!-- The main stylesheet of this template. All Bootstrap overwrites are defined in here -->
    <?php print($this->tag->stylesheetLink("css/main.css"))?>

	<!-- The themes stylesheet of this template (for using specific theme color in individual elements - must included last) -->
    <?php print($this->tag->stylesheetLink("css/themes.css"))?>

    <!-- tema personalizado para imannova -->

    <?php print($this->tag->stylesheetLink("css/custom.css"))?>
    <?php print($this->tag->stylesheetLink("css/custom-nav.css"))?>
    <?php print($this->tag->stylesheetLink("css/custom-profile-ui.css"))?>
	<!-- END Stylesheets -->

	<?php
		if(isset($addCss)){
			foreach($addCss as $link){
				print($this->tag->stylesheetLink($link));
			}
		}
	?>
	
	<!-- Modernizr (browser feature detection library) & Respond.js (enables responsive CSS code on browsers that don't support it, eg IE8) -->
	<?php print($this->tag->javascriptInclude("js/vendor/modernizr-respond.min.js"))?>


</head>
<body class="page-loading">
	<div class="page-wrapper">

		<div id="page-container" class=" <?php print(isset($sideBar) && $sideBar!=null? 'sidebar-visible-lg sidebar-partial':'') ?>  style-alt ">

            <!-- habilita side bar -->
        	<?php if(isset($sideBar) && $sideBar!=null) 
				echo $this->view->render($sideBar,array('pcData'=>$pcData, 'sideBarSel' => $sideBarSel));
			?>
			<!-- fin side bar -->


	        <!-- Main Container -->
	        <div id="main-container">

	            <header class="navbar navbar-default ">
	                <?php if(isset($topMenu) && $topMenu!=null) 
						echo $this->view->render($topMenu,array('pcData'=>$pcData, 'menuSel' => $menuSel));
					?>
	            </header>
	            <!-- END Header -->


	            <!-- Page Content -->
	            <div id="page-content" class="clearfix">
	            	<div class="content-width">


		            <?php if(isset($pcView) && $pcView!=null) 
							echo $this->view->render($pcView,array('pcData'=>$pcData));
					?>
					</div>
	            </div>
	            <!-- END Page Content -->

	            <!-- Footer -->
	            <footer class="clearfix">
	                <div class="pull-right">
	                	Propiedad de <?php print($this->config->appAutor)?> <i class="fa fa-heart text-danger"></i> by <a href="http://zentagroup.com" target="_blank"><?php print($this->config->appAutor)?></a>
	                	
	            	</div>
		            <div class="pull-left">
		                <span id="year-copy"></span> 2016 &copy; <a href="" ><?php print($this->config->appTitle)?></a>
		            </div>
	            </footer>
	            <!-- END Footer -->
	        </div>
       		<!-- END Main Container -->
		</div>
    	<!-- END Page Container -->

		<!-- Scroll to top link, initialized in js/app.js - scrollToTop() -->
		<a href="#" id="to-top"><i class="fa fa-angle-double-up"></i></a>
	</div>

	<!-- Remember to include excanvas for IE8 chart support -->
	<!--[if IE 8]><?php print($this->tag->javascriptInclude("js/helpers/excanvas.min.js"))?><![endif]-->

	<!-- jQuery, Bootstrap.js, jQuery plugins and Custom JS code -->
	<?php print($this->tag->javascriptInclude("js/vendor/jquery-1.11.3.min.js"))?>
	<?php print($this->tag->javascriptInclude("js/vendor/bootstrap.min.js"))?>
	<?php print($this->tag->javascriptInclude("js/plugins.js"))?>

	<script >
	$(document).ready(function(){
	    $("a").tooltip();
	});
	</script>

	<?php
	if(isset($jsScript) && $jsScript!=null){
	?>
	<script>
	<?php print($jsScript)?>
	</script>
	<?php
		}
	?>		
	<?php
		if(isset($addJs) && $addJs!=null){
			foreach($addJs as $link){
	?>
	<?php print($this->tag->javascriptInclude($link))?>
	<?php
			}
		}
	?>
	<?php
	if(isset($jsPosScrt) && $jsPosScrt!=null){
	?>
	<script>
	<?php print($jsPosScrt)?>
	</script>
	<?php
		}
	?>	


</body>
</html>